### ISSUE TITLE
[Suggestion] Show ViewProfilePicture button on hover

### ISSUE THREAD

**Issue by maenDisease** [Skamt/BDAddons#3]
Have the button appear when hovering over the profile like the nitro button
```css
.VPP-Button {
    opacity: 0;
    -webkit-transform: translate3d(0,-5px,0);
    transform: translate3d(0,-5px,0);
    -webkit-transition: opacity .15s ease-out,-webkit-transform .15s ease-out;
    transition: opacity .15s ease-out,-webkit-transform .15s ease-out;
}

.profileColors-3Y0XaR:hover .VPP-Button {
    opacity: 1;
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    outline: 1px solid transparent;
}
```
